# Tensor

In [1]:
import torch

In [2]:
print(torch.__version__)

1.1.0


## Tensor Basic

In [3]:
# float tensor가 default 로 random generation
x = torch.Tensor(2, 3)
print(x)

tensor([[8.4078e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [4]:
print("Tensor Type : ", type(x))
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

Tensor Type :  <class 'torch.Tensor'>
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [7]:
print("Tensor Size : ", x.shape)

Tensor Size :  torch.Size([2, 3])


In [8]:
x = torch.zeros(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
x.type(), x.shape

('torch.FloatTensor', torch.Size([2, 3]))

In [10]:
x = torch.ones(2, 3)
print(x, x.type(), x.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.FloatTensor torch.Size([2, 3])


In [11]:
x = torch.rand(2, 3) #0 ~ 1 사이의 랜덤 float
print(x, x.type(), x.shape)

tensor([[0.9732, 0.5847, 0.6515],
        [0.7490, 0.6166, 0.6051]]) torch.FloatTensor torch.Size([2, 3])


In [12]:
x = torch.randn(2, 3) #random normal dist.
print(x, x.type(), x.shape)

tensor([[ 0.0265,  1.5243,  0.9513],
        [ 1.4876, -2.1170, -1.7688]]) torch.FloatTensor torch.Size([2, 3])


In [13]:
x = torch.eye(3, 3)
print(x, x.type(), x.shape)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]) torch.FloatTensor torch.Size([3, 3])


In [14]:
x = torch.Tensor([[1, 2, 3], [1, 2, 3]])
print(x, x.type(), x.shape)

tensor([[1., 2., 3.],
        [1., 2., 3.]]) torch.FloatTensor torch.Size([2, 3])


In [16]:
x = torch.IntTensor(2, 3)
print(x, x.type(), x.shape)

tensor([[1698181221,  758264881,  808674402],
        [ 926102573,  945892709,  959264052]], dtype=torch.int32) torch.IntTensor torch.Size([2, 3])


## Tensor & Numpy

In [17]:
import numpy as np

In [23]:
x = np.array([[1, 2, 3], [1, 2, 3]])
print(x, type(x))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


In [24]:
xn = torch.from_numpy(x) #longtensor
print(xn, xn.type(), xn.shape)

tensor([[1, 2, 3],
        [1, 2, 3]]) torch.LongTensor torch.Size([2, 3])


In [27]:
x = torch.Tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [28]:
print(x[:, :])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [29]:
x[1:, :]

tensor([[ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [30]:
x_rows = torch.split(x, split_size_or_sections=1, dim=0) #x를 한개씩 행으로 잘라줘
print(x_rows)

(tensor([[1., 2., 3., 4.]]), tensor([[5., 6., 7., 8.]]), tensor([[ 9., 10., 11., 12.]]))


In [31]:
x_cols = torch.split(x, split_size_or_sections=2, dim=1)
print(x_cols)

(tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]]), tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]]))


In [35]:
print(x_cols[0].shape)

torch.Size([3, 2])


In [34]:
x_rows[0].shape

torch.Size([1, 4])

## Merging

In [36]:
torch.cat(x_rows, dim=0)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [40]:
torch.cat(x_rows, dim=1)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [41]:
x_new = torch.stack(x_cols, dim=0)
print(x_new, x_new.type(), x_new.shape)

tensor([[[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]],

        [[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]]) torch.FloatTensor torch.Size([2, 3, 2])


### Reshaping

In [43]:
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [42]:
x.view(4, 3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [44]:
x.view(3, 3)

RuntimeError: shape '[3, 3]' is invalid for input of size 12

In [45]:
x.view(-1, 2) #-1은 알아서 자동으로 바뀌게 맡기는 것

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [46]:
x.view(3, -1)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [47]:
x.view(2, 1, -1)

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])

In [49]:
x.view(2,-1)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

In [52]:
#cuda 확인
print("현재 Cuda 사용 가능한 Device 개수 :", torch.cuda.device_count())
print("현재 Cuda 사용 가능 여부 :", torch.cuda.is_available())
print("현재 사용 중인 Cuda Device :", torch.cuda.current_device())
print("현재 Cuda Device 이름 :", torch.cuda.get_device_name(0))
print("현재 Cuda Device의 사용 가능한 메모리 :", torch.cuda.max_memory_allocated(device=0), "bytes")
print("현재 Cuda Device의 사용 중인 메모리 :", torch.cuda.memory_allocated(device=0), "bytes")

현재 Cuda 사용 가능한 Device 개수 : 0
현재 Cuda 사용 가능 여부 : False


AssertionError: Torch not compiled with CUDA enabled

## Tensor Calculation

In [54]:
x = torch.Tensor([[1,2,3], [4,5,6]])
y = torch.Tensor([[1,1,1], [2,2,2]])
print('x :', x)
print('y :', y)

x : tensor([[1., 2., 3.],
        [4., 5., 6.]])
y : tensor([[1., 1., 1.],
        [2., 2., 2.]])


In [55]:
z = torch.add(x, y)
print('z :', z)
print('x + y : ', x+y)

z : tensor([[2., 3., 4.],
        [6., 7., 8.]])
x + y :  tensor([[2., 3., 4.],
        [6., 7., 8.]])


In [56]:
print(x-2)
print(2*x)

tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [57]:
print('x*y: ', x*y)

x*y:  tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])


In [59]:
print('x**2 : ',x**2)

x**2 :  tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


In [60]:
print('x.log() : ', torch.log(x))

x.log() :  tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])


In [61]:
print('x.sqrt() :', torch.sqrt(x))

x.sqrt() : tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])


In [62]:
print('x % 2 : ', x % 2)

x % 2 :  tensor([[1., 0., 1.],
        [0., 1., 0.]])


## Tensor Casting

In [64]:
x, x.type()

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), 'torch.FloatTensor')

In [65]:
x.type(torch.DoubleTensor), x

(tensor([[1., 2., 3.],
         [4., 5., 6.]], dtype=torch.float64), tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [66]:
x.int()

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

## Like Fn

In [69]:
x = torch.Tensor([[-1, 2, -3], [4, -5, 6]])
print(x)

tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])


In [70]:
y = torch.zeros_like(x)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [71]:
z = torch.ones_like(x)
print(z)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [72]:
r = torch.rand_like(x)
print(r)

tensor([[0.8613, 0.4702, 0.8035],
        [0.5967, 0.4435, 0.1570]])


# Review

In [4]:
#Tensor 기초 선언
x = torch.Tensor(2,3)
print(x, x.type(), x.shape)
# torch.Tensor 기초 선언은 float으로 선언됨

tensor([[ 0.0000e+00,  2.0000e+00,  1.2114e+26],
        [-1.0845e-19,  8.4078e-45,  0.0000e+00]]) torch.FloatTensor torch.Size([2, 3])


In [6]:
print(torch.zeros(2,3))
print(torch.ones(2,3))
print(torch.rand(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.7050, 0.4093, 0.5972],
        [0.9322, 0.4876, 0.1849]])


In [7]:
import numpy as np

In [12]:
#numpy => tensor
x = np.array([[1,2,3], [4,5,6]])
print(x, type(x))

x_tensor = torch.from_numpy(x)
print(x_tensor, type(x_tensor))

#tensor => numpy
x_numpy = x_tensor.numpy()
print(x_numpy, type(x_numpy))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
tensor([[1, 2, 3],
        [4, 5, 6]]) <class 'torch.Tensor'>
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [13]:
#view
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x, type(x), x.shape)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]]) <class 'torch.Tensor'> torch.Size([3, 4])


In [22]:
y = x.view(-1, 1)
print(y, type(y), y.shape)

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.]]) <class 'torch.Tensor'> torch.Size([12, 1])


In [23]:
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [25]:
torch.zeros_like(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
torch.rand_like(x)

tensor([[0.4376, 0.5689, 0.4596, 0.2732],
        [0.8021, 0.9904, 0.4859, 0.3818],
        [0.8642, 0.5935, 0.3179, 0.4955]])